#!/bin/sh

PATH=/bin:/sbin:/usr/bin:/usr/sbin

if [ -z "$SSH_PUBLIC_KEY" -a -z "$EC2_PUBLIC_KEY" ]; then
  exit 0
fi

mkdir -m0700 /root/.ssh
cat /dev/null > /root/.ssh/authorized_keys

if [ -n "$SSH_PUBLIC_KEY" ]; then
  echo "$SSH_PUBLIC_KEY" >> /root/.ssh/authorized_keys
fi

if [ -n "$EC2_PUBLIC_KEYS" ]; then
  echo "$EC2_PUBLIC_KEY" >> /root/.ssh/authorized_keys
fi

chmod 600 /root/.ssh/authorized_keys

exit 0
